trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line'

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'adminportal_rsa.pub'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'adminportal-rg-service-connection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'adminportal-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'adminportalstorageac'
    backendAzureRmContainerName: 'adminportalcontainer'
    backendAzureRmKey: 'adminportal-dev.tfstate'


- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/kubernetes'
    environmentServiceName: 'adminportal-rg-service-connection'
    #commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'